create table  Person(
                        person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        fio varchar(200) NOT NULL UNIQUE,
                        year_of_birth int NOT NULL CHECK ( year_of_birth>1900)
)

create table Book(
    book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_name varchar(100) NOT NULL ,
    author varchar(100),
    year_of_creation int,
    person_id int NOT NULL REFERENCES Person(person_id)
)